---
# role: ansible-role-postgresql
# file: tasks/main.yml

- name: "Tasks for ansible-role-postgresql"
  ansible.builtin.include_tasks: tasks.yml
  when: postgresql_role_enabled | bool
  tags:
    - postgresql:config
    - postgresql:db
    - postgresql:initdb
    - postgresql:pkg
    - postgresql:user
