---
# role: ansible-role-postgresql
# file: tasks/tasks.yml

- name: "Set distribution dependent variables"
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: "Install packages for ansible-role-postgresql"
  package:
    name: "{{ postgresql_python_libs + postgresql_packages }}"
    state: present

- name: "Configure locales for Debian-based systems"
  block:
    - name: "Ensure locales are configured"
      locale_gen: "name={{ item }} state=present"
      loop: "{{ postgresql_locales }}"
      register: locale_gen_result

    - name: "Restart postgresql after locales changed"
      service:
        name: "{{ postgresql_daemon }}"
        state: restarted
      when: locale_gen_result.changed
  when: ansible_os_family == 'Debian'

- name: Initialize postgresql database
  import_tasks: init.yml

- name: Configure postgresql database
  import_tasks: config.yml
