---
# role: ansible-role-postgresql
# file: handlers/main.yml

- name: reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
    enabled: true
