---
# role: ansible-role-postgresql
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: pg-default
    image: ${MOLECULE_DIST:-"jam82/molecule-ubuntu:18.04"}
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    tty: False
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        postgresql_enabled: True
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: True
    sudo: True
